### ISSUE TITLE
core_frontend scripts

### ISSUE THREAD

**Issue by Jake-NotTheMuss** [seriousyt/t7-source#1]
Can you add the core_frontend gsc scripts (from core_frontend_patch.ff)? I'm using this repo for some regex search stuff and I don't want to miss those. (I'm using this repo because the formatting is uniform and because it has all the compiler-generated foreach keys)

**Comment by shiversoftdev** [comment]
yeah i can

**Comment by Jake-NotTheMuss** [comment]
awesome
